services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./storage:/app/storage
      - ./bootstrap/cache:/app/bootstrap/cache
      - ./public:/app/public # 🚨 Monta public local al contenedor
    expose:
      - "9000"
    depends_on:
      - postgres
    networks:
      - backend

  vite:
    build:
      context: .
      dockerfile: Dockerfile.vite
    container_name: vite-app
    working_dir: /app
    ports:
      - "5173:5173"
    networks:
      - backend
    depends_on:
      - app

  postgres:
    image: postgres:16
    container_name: postgres_db_2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=fCastillo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  webserver:
    image: nginx:alpine
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/app/public # 🚨 Monta public local al contenedor de nginx
    depends_on:
      - app
      - vite
    networks:
      - backend

  pgadmin_2:
    image: dpage/pgadmin4
    container_name: pgadmin_2
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin_2
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  pgdata:
  pgadmin_data:


networks:
  backend:
    driver: bridge
